set -g mouse on
setw -g mode-keys vi

# color declaration
C_GREY=colour245
C_DARK_GREY=colour236
C_BLACK=black
C_MAGIC=colour118
C_WHITE=white
C_BLUE=blue
C_DARK_BLUE=colour17


# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1

# Renumbering windows (whenever they closed or else)
set -g renumber-windows on

# remap prefix from 'C-b' to 'C-z'
unbind C-b
set-option -g prefix C-z
bind-key C-z send-prefix

# bind reloading config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# change windows-line separator
set -g window-status-separator ' '

# change position of windows list
set -g status-justify absolute-centre

# change inactive window formatting
set -g window-status-format '\
#[bg=#{C_BLACK}]#[fg=#{C_GREY}]#(~/tmuxconf/symbol.sh round_lh)\
#[bg=#{C_GREY}]#[fg=#{C_BLACK}]#{window_index}#{window_flags}\
#[bg=#{C_BLACK}]#[fg=#{C_GREY}]#(~/tmuxconf/symbol.sh round_rh)'

# change active window formatting
set -g window-status-current-format '\
#[bg=#{C_BLACK}]#[fg=#{C_MAGIC}]#(~/tmuxconf/symbol.sh round_lh)\
#[bg=#{C_MAGIC}]#[fg=#{C_BLACK}]#{window_index}#{window_flags}\
#[bg=#{C_BLACK}]#[fg=#{C_MAGIC}]#(~/tmuxconf/symbol.sh round_rh)'

# change status right/left lenght
set -g status-right-length 150
set -g status-left-length 50

# change position of status bar to TOP
set -g status-position bottom 

# change colors of pane separators
set -g pane-border-style 'fg=#{C_DARK_GREY}'
set -g pane-active-border-style 'fg=#{C_MAGIC}'

# change color of status bar
set -g status-bg "$C_BLACK"
set -g status-fg "$C_WHITE"

# change status-left
set -g status-left '\
#[bg=#{C_BLUE}]#[fg=#{C_BLACK}] #H \
#[bg=#{C_DARK_BLUE}]#[fg=#{C_BLUE}]#(~/tmuxconf/symbol.sh rh)\
#[bg=#{C_DARK_BLUE}]#[fg=#{C_WHITE}] #{window_name} \
#[bg=#{C_BLACK}]#[fg=#{C_DARK_BLUE}]#(~/tmuxconf/symbol.sh rh)'

set -g status-right '\
#[bg=#{C_BLACK}]#[fg=cyan]#(~/tmuxconf/symbol.sh lh)\
#[bg=cyan]#[fg=#{C_BLACK}] %H:%M '
